export const classNames = {
    arrow: 'slidy-arrow',
    autoplay: 'slidy-autoplay',
    counter: 'slidy-counter',
    img: 'slidy-img',
    nav: 'slidy-nav',
    'nav-item': 'slidy-nav-item',
    overlay: 'slidy-overlay',
    progress: 'slidy-progress',
    'progress-handle': 'slidy-progress-handle',
    root: 'slidy',
    slide: 'slidy-slide',
    slides: 'slidy-slides',
    thumbnail: 'slidy-thumbnail',
    thumbnails: 'slidy-thumbnails',
};
