name: build-and-deploy

on:
  push:
    branches: ['master']
    paths:
      - www/**
  pull_request:
    branches: ['master']
    paths:
      - www/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm build:www
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: www/build/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - run: rm -rf *
      - uses: actions/download-artifact@v3
        with:
          name: build
      - uses: EndBug/add-and-commit@v9.0.0
        with:
          default_author: github_actions
          message: Deployment
